import "@repo/ui/globals.scss";
import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Docs",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <div className="flex justify-center items-center relative min-h-screen w-full">
      <div className="absolute inset-0">
        <Image
          src="/images/test1.webp"
          alt="background"
          className="w-full h-full object-cover"
          fill
        />
      </div>
      <div className="w-full flex justify-center">{children}</div>
    </div>
  );
}
