version: "3.8"

services:
  core:
    build:
      context: .
      dockerfile: apps/core/Dockerfile2
    ports:
      - "3000:3000"

    environment:
      - NODE_ENV=production
    tty: true # Ensures real-time logs
    stdin_open: true # Keeps stdin open
