services:
  core:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/core/Dockerfile
    restart: always
    ports:
      - "5000:3000"
    networks:
      - app-network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app-network:
    driver: bridge
