name: PR Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: client
    steps:
      - name: Cleanup Docker Preview Container
        run: |
          sudo docker stop preview-pr-${{ github.event.number }} || true
          sudo docker rm preview-pr-${{ github.event.number }} || true
          sudo docker rmi mrbadri/pixel-client:pr-${{ github.event.number }} || true
