name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: client-runner  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image using Docker Compose
        run: sudo docker-compose build

      - name: Tag Docker Image
        run: sudo docker tag pixel-client-core mrbadri/pixel-client:latest

      - name: Push Docker Image to Docker Hub
        run: |
          sudo docker login -u mrbadri -p ${{ secrets.DOCKER_TOKEN }}
          sudo docker push mrbadri/pixel-client:latest

  deploy:
    runs-on: client-runner
    needs: build  
    steps:
      - name: Pull and Restart Container
        run: |
          sudo docker pull mrbadri/pixel-client:latest
          sudo docker stop pixel-client || true
          sudo docker rm pixel-client || true
          sudo docker run -d --name pixel-client -p 3000:3000 mrbadri/pixel-client:latest
