name: Docker CI/CD - Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image using Docker Compose
        run: sudo docker-compose build

      - name: Tag Docker Image
        run: sudo docker tag pixel-client-core mrbadri/pixel-client:latest

      - name: Push Docker Image to Docker Hub
        run: |
          sudo docker login -u mrbadri -p ${{ secrets.DOCKER_TOKEN }}
          sudo docker push mrbadri/pixel-client:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Pull the Latest Docker Image
        run: sudo docker pull mrbadri/pixel-client:latest

      - name: Stop and Remove Existing Container (if exists)
        run: |
          if [ $(docker ps -aq -f name=pixel-client) ]; then
            echo "Stopping and removing existing container..."
            sudo docker stop pixel-client
            sudo docker rm pixel-client
          else
            echo "No existing container found. Skipping removal."
          fi

      - name: Run the New Container
        run: |
          sudo docker run -d --name pixel-client -p 3000:3000 mrbadri/pixel-client:latest
