name: Docker Compose Build & Push

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: self-hosted # Uses the organization's self-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image with Compose
        run: |
          docker compose build
          docker compose push
