name: Create Branch on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Add issue comment - Branch is Creating...
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
               -d '{"body": "Branch is Creating..."}'
      - name: Extract issue details
        id: issue
        run: |
          TITLE="${{ github.event.issue.title }}"
          NUMBER="${{ github.event.issue.number }}"
          # Extract the first word as issue type (e.g., "bugfix: Fix UI" → "bugfix")
          ISSUE_TYPE=$(echo "$TITLE" | awk '{print $1}' | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-')
          ISSUE_TYPE=$(echo "$ISSUE_TYPE" | sed 's/:$//')
          # Allowed issue types
          ALLOWED_TYPES="feat|fix|bugfix|chore|refactor|docs|test|style|perf|ci|build"
          # If issue type is empty or unrecognized, default to "feat"
          if [[ -z "$ISSUE_TYPE" || ! "$ISSUE_TYPE" =~ ^($ALLOWED_TYPES)$ ]]; then
            ISSUE_TYPE="feat"
          fi

          # Remove issue type from the title and format safely
          SAFE_TITLE=$(echo "$TITLE" | sed "s/^$ISSUE_TYPE[:]* *//" | tr ' ' '-' | tr -cd '[:alnum:]-')

          # Construct the branch name
          BRANCH_NAME="${ISSUE_TYPE}/#${NUMBER}-${SAFE_TITLE}"

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "Branch to be created: $BRANCH_NAME"

      - name: Create new branch
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git fetch origin
          git checkout -b $BRANCH_NAME origin/main
          git push origin $BRANCH_NAME
      - name: Update issue with checkout command
        run: |
          CHECKOUT_COMMAND="\`\`\`bash\ngit fetch origin\ngit checkout $BRANCH_NAME\n\`\`\`"
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
               -d "{\"body\": \"Branch created successfully! Use the following command to check it out:\n\n$CHECKOUT_COMMAND\"}"
      - name: Link branch to issue in the Development section
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/development \
               -d "{\"head_branch\": \"$BRANCH_NAME\"}"
    continue-on-error: true
  error-handling:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Add error comment to issue
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
